Add books page test cases
dimola/Ecomm_Testing pull request #11
Opened 2019-02-08 07:23 UTC by IvayloStoyanov10

- Structure is still different from the one Yakim showed us in the last conversation
- Merge conflicts need to be solved
- Elements need to be found by css
- Content and verification test cases need to be moved to another class, as mentioned in the newer structure

2019-02-19 13:26 UTC, jakimcho requested changes

2019-02-19 13:26 UTC, jakimcho commented on features/ContentVerification.feature
> +	Then The header the books categories and the search field are displayed
@upetkova This step is little odd. Can you correct the wording. Also, don't use capitalized letters after When, Then, Given, etc. Just follow the normal speaking language rules -> `Then the header...`

2019-02-19 13:26 UTC, jakimcho commented on src/main/java/pageObjects/CategoryPage.java
> +	public boolean checkSideMenu() {
@upetkova since this is a PageObject and not an actual test, use appropriate names for these functions, like `isSideMenuDisplayed`

2019-02-19 13:26 UTC, jakimcho commented on src/main/java/pageObjects/CategoryPage.java
> +	public boolean checkProductList() {
Use proper names

2019-02-19 13:26 UTC, jakimcho commented on src/main/java/pageObjects/CategoryPage.java
> +	public boolean checkSearchForm() {
Use proper names

2019-02-19 13:26 UTC, jakimcho commented on src/main/java/pageObjects/BooksPage.java
> +	public boolean checkSearchCriterias() {
What should this method do? Also use proper names

2019-02-19 13:26 UTC, jakimcho commented on src/main/java/pageObjects/GeneralPage.java
> +	public boolean checkHeaderData() {
Use proper names and all these checks I thing should happen in the test class with assertion in order to know which exactly element is missing

2019-02-19 13:36 UTC, upetkova commented on src/main/java/pageObjects/BooksPage.java
> +	public boolean checkSearchCriterias() {
This should check according to the test case if in the Search Form that there are 4 search criteria: Author, Title, Publisher, ISBN. I will change it to isAllSearchCriteriaTextboxesDisplayed?

2019-02-20 07:33 UTC, upetkova commented on features/ContentVerification.feature
> +	Then The header the books categories and the search field are displayed
Ok! I'm not good with wording but I've changed that in the new commit as:
Then I should see the header also book categories and search criterias
I tried to be less descriptive even though I'm still not sure how much details we should put here.

2019-02-20 07:34 UTC, upetkova commented on src/main/java/pageObjects/CategoryPage.java
> +	public boolean checkSideMenu() {
Agree! I've change the names with similar ones for all the page elements that should be displayed on the pages.

2019-02-20 07:35 UTC, upetkova commented on src/main/java/pageObjects/CategoryPage.java
> +	public boolean checkProductList() {
Done.

2019-02-20 07:35 UTC, upetkova commented on src/main/java/pageObjects/CategoryPage.java
> +	public boolean checkSearchForm() {
Done.

2019-02-20 07:37 UTC, upetkova commented on src/main/java/pageObjects/BooksPage.java
> +	public boolean checkSearchCriterias() {
I've separated all page elements into the according pages and created methods isSomethingDisplayed() for them so I can check them in the Assertions in the tests with proper messages if something is not displayed.

2019-02-20 07:37 UTC, upetkova commented on src/main/java/pageObjects/GeneralPage.java
> +	public boolean checkHeaderData() {
Done.

2019-02-20 11:13 UTC, jakimcho requested changes

2019-02-20 11:13 UTC, jakimcho commented on features/ContentVerification.feature
> +	Then I should see the header also book categories and search criterias
@upetkova This is one step that check a lot of things, I would split it like that:
```
Then I should see the books page
And I should see all book filtering options
```
Or something similar

2019-02-20 13:40 UTC, upetkova approved these changes

2019-02-21 07:10 UTC, upetkova commented on features/ContentVerification.feature
> +	Then I should see the header also book categories and search criterias
Done.

2019-02-21 07:14 UTC, jakimcho approved these changes

2019-02-21 07:14 UTC, merged