FindBy xPath changed to FindBy ID or CSS
dimola/Ecomm_Testing pull request #4
Opened 2019-01-25 13:56 UTC by IvayloStoyanov10

Username is found by ID
Password and Login button are found by CSS

2019-01-25 17:03 UTC, jakimcho requested changes
@IvayloStoyanov10 Не е нужно за очевидни неща да слагаш коментари, не че пречи но е безмисленно.

- Друго, синхронизирайте се с Димо за метода `getLoginPage(WebDriver driver)`
   - От към имплементация
   - Ако този метод има за цел да навигира то логин страницата, то името му в момента е подвеждащо. сменете го на `open()` . Идеята е че после в самият test case ще изглежда така: 
```
loginPage.open();
```

2019-01-25 17:03 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +@FindBy(id = "username") //id
Защо ти е този коментар `id` :-D ?

2019-01-25 17:03 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
>  	driver.get("http://acme.qualityhouse.bg/build3/index.php?page=login");
@IvayloStoyanov10 @dimola  Синхронизирайте се за този метод

2019-01-28 09:14 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/LoginPage.java
> +@FindBy(id = "username") //id
Fixed - бях си ги добавил преди да започна да ги променям, за да знам кое като какво да го търся

2019-01-28 09:14 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/LoginPage.java
>  	driver.get("http://acme.qualityhouse.bg/build3/index.php?page=login");
Fixed - Променено е на open()

2019-01-28 09:26 UTC, jakimcho requested changes

2019-01-28 09:26 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +public void open(WebDriver driver) {
Тука защо ви е параметер driver?.
Нали имате референция към driver-a в даденият page object?
method-a трябва да изглежда така:
```
public void open() {
    this.driver.get("http://acme.qualityhouse.bg/build3/index.php?page=login");
}

2019-01-28 09:26 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		login.open(driver);
След като оправиш метода open в LoginPaga.java трябва само да викнеш 
```
login.open();
```

2019-01-28 09:48 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/LoginPage.java
> +public void open(WebDriver driver) {
Fixed - параметрите са премахнати

2019-01-28 09:49 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +		login.open(driver);
Fixed - параметрите са премахнати

2019-01-28 09:54 UTC, jakimcho approved these changes

2019-01-28 09:54 UTC, merged