Reading from config file
dimola/Ecomm_Testing pull request #5
Opened 2019-01-25 15:04 UTC by dimola

Changes made according to your latest comments:
1) configs//Configuration.properties -> configs/Configuration.properties
2) New methods were created in ConfigFileReader. Now url`s are taken from Configuration.properties.

2019-01-25 17:11 UTC, jakimcho requested changes
@dimola Малко не си ме разбрал
в `Configuration.properties` сетваш нещата =>:
```
url = http://acme.qualityhouse.bg/build3
login-page-path = /index.php?page=login
register-page-path = ......
```

После в съответният page object : 
```
calss LoginPage {
   private String url;
   LoginPage(WebDriver driver){
      .......................
      this.url = ConfigurationReader.getHost() + ConfigurationReader.getLoginPagePath()
   }

   ...............
  public LoginPage open(){
     this.driver.open(this.url);
     return this;
  }

  public String getUrl(){
     return this.url;
   }
}
```

2019-01-25 17:11 UTC, jakimcho commented on configs/Configuration.properties
> +loginUrl=http://acme.qualityhouse.bg/build3/index.php?page=login
@dimola Тука по-скоро имах в предвид, че трябва да сложиш само пътя до страницата, а не целият URL.
После в кода ще сформираш правилният URL към страницата, като конкатинираш `url` и `login-page-path`:
java code:
```
 loginPageUrl = app.propperties.get("url") +  app.propperties.get("login-page-path")
```

Идеята, е че, ако ти се наложи да смениш host-name-а на web application-a, ще пипнеш само на едно място и всичко ще е ок.

2019-01-25 17:11 UTC, jakimcho commented on src/main/java/dataProviders/ConfigFileReader.java
> +		String loginUrl = properties.getProperty("loginUrl");
@dimola виж коментара ми в `Configuration.properties`

2019-01-25 17:11 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +	pageUrl = configFileReader.getApplicationUrl() + configFileReader.getLoginUrl();
@dimola Това сработило ли е?
Това би трябвало да генерира url:
``http://acme.qualityhouse.bg/build3http://acme.qualityhouse.bg/build3/index.php?page=login`

2019-01-25 17:11 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +	driver.get(loginUrl);
@dimola Тука идеята е да `pageUrl` в `driver.get()`. и метода `getLoginUrl()` да се дефинира в `LoginPage.java` под името `getUrl` и да връща стойността на `pageUrl`

2019-01-28 10:58 UTC, dimola commented on configs/Configuration.properties
> +loginUrl=http://acme.qualityhouse.bg/build3/index.php?page=login
Промяната в configurations.properties е направена.

2019-01-28 11:02 UTC, dimola commented on src/main/java/pageObjects/LoginPage.java
> +	pageUrl = configFileReader.getApplicationUrl() + configFileReader.getLoginUrl();
Да, така се е получило. Мисля, че би трябвало да е ок в момента.

2019-01-28 11:05 UTC, dimola commented on src/main/java/pageObjects/LoginPage.java
> +	driver.get(loginUrl);
Не съм убеден, че разбирам добре, точно какво трябва да се направи тук.
За момента го промених така:

`public void getLoginPage(WebDriver driver) {
	this.pageUrl = configFileReader.getHost() + configFileReader.getLoginPagePath();
	driver.get(pageUrl);
}`

2019-01-28 13:01 UTC, jakimcho approved these changes

2019-01-28 13:01 UTC, merged