Updated TC 1, Added TC2
dimola/Ecomm_Testing pull request #6
Opened 2019-01-30 10:03 UTC by dimola

1) TC1  Login with valid credentials - Created method (isHomePageOnFocus) for the last step in the Test Case. In order to do that, I had to add the following configurations : 
- Updated configuration.properties with new home_page_path
- Created new method(getHomePagePath) in ConfigFileReader
- Created new Page Object - HomePage

2) Added new TC2 - Login with invalid credentials.

2019-01-30 13:23 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +		driver.close();
Is there a reason why `Driver.close() ` is used instead of `Driver.quit()`

2019-01-30 13:48 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/HomePage.java
> +	private WebElement bookCategoryOption;
I do not see where this is used. Can we remove it?

2019-01-30 17:58 UTC, jakimcho requested changes

2019-01-30 17:58 UTC, jakimcho commented on configs/Configuration.properties
> +home-page-path=index.php?page=home
@dimola Това работи ли така? При положение че `url`-ът ти не завършва с `/` пътищата към страниците трябва за започват с `/` . Виж как е на `login-page-path`

2019-01-30 17:58 UTC, jakimcho commented on src/main/java/dataProviders/ConfigFileReader.java
>  			throw new NotFoundException("Configuration.properties not found at " + propertyFilePath);
@dimola тука моя грешка, че не обърнах повече внимание на кода първият път. След като си прихванал грешката, и искаш да терминираш процеса на изпълнение, ползвай `System.exit()`.  Иначе може да се оплетеш в stack trace-а после. Демек по-правилно е да направиш в случая, когато го няма propertyFile:
```
... 
}catch (FileNotFoundException e) {
			e.printStackTrace();
                        System.err.println("Къде си тръгнал в Б група без топка?...")
                         System.exit();
.........
```

2019-01-30 17:58 UTC, jakimcho commented on src/main/java/dataProviders/ConfigFileReader.java
> +			throw new NotFoundException("implicitlyWait not specified in the Configuration.properties file.");
@dimola Тука бих ти предложиш да не прекъсваш automation-a само защото в propertyFile-a не е дефиниран 'implicitWait'. Ако не е дефиниран, ползвай default-ен, например 5000.

2019-01-30 17:58 UTC, jakimcho commented on src/main/java/pageObjects/HomePage.java
> +		if (driver.findElements(By.xpath("//*[@id=\"main-big-col\"]/h3")).size() != 0) {
@dimola it is little unclear what exactly is happening. You may implement it in more appropriate way:
```
.....
public class HomePage {

@FindBy(xpath = "//*[@id=\"main-big-col\"]/h3")
private WebElement pageHeadingTitle;
......
public boolean isHomePageOnFocus() {
    boolean result = false
    try {
        result = this.pageHeadingTitle.isDisplayed() && this.pageHeadingTitle.getText().equals("Home");
    }catch (Throwable e){
        System.error("Problem while checking if Home Page Heading is displayed: " + e.getMessage());
    }

    return result;
}

2019-01-30 17:58 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +	public void isLoginPageOnFocus() {
@dimola Виж ми коментара от `HomePage-a`

2019-01-30 17:58 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +	@Test
@dimola Какво правят `@Test` и `@BeforeClass` тук?
Те не са ли анотации за `Junit` тестовете?

2019-01-30 17:58 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		driver.close();
@dimola Защо въобще трябва да затваряш browser-a в step definition? По скоро това трябва да се случва в coocomber hook method:
https://docs.cucumber.io/cucumber/api/#after
https://www.tutorialspoint.com/cucumber/cucumber_hooks.htm

2019-01-30 17:58 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		loginPage.isLoginPageOnFocus();
@dimola Това няма да ти даде информация дали test-a fail-a. Виж коментарите които съм сложил за `isLoginPageOnFocus()` и `isHomePageOnFocus` и после ползавй Assertions за да валидираш резултатите:
https://www.tutorialspoint.com/junit/junit_using_assertion.htm

2019-01-30 17:58 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		homePage.isHomePageOnFocus();
@dimola Това няма да ти даде информация дали test-a fail-a. Виж коментарите които съм сложил за `isLoginPageOnFocus()` и `isHomePageOnFocus()` и после ползавй Assertions за да валидираш резултатите:
https://www.tutorialspoint.com/junit/junit_using_assertion.htm

2019-01-30 17:58 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +	@When("^I type invalid username \"(.*)\"$")
@dimola Каква е разликата в имплементацията на този метод и на `I_type_valid_username` ?
Единствено мапинг-а `^I type invalid username \"(.*)\"$` се различава.
Аз бих оставил само единият метод, бих го кръстил `I_type_username`, и мапинг-а ще е `^I type username \"(.*)\"$`.
После и в двата сценария, позитивният и негативният ще имам:
```
Scenario: Successful login
....
When I type username "валидно име"
....

```
и
```
Scenario: Unsuccessful login
....
When I type username "невалидно име"
....

```

2019-01-30 17:58 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +	@When("^I type invalid username \"(.*)\"$")
@dimola същото се отнася и за другите полета. Силата на cucumber е че с малко имплементирани стъпки, можеш да направиш множество тестове, ако тръгнеш да детайлизираш дали е валидно, нагативно и тн ще е мн тромаво и общо взето ще има copy-paste на един и същи код в различни по име method-и

2019-01-31 09:14 UTC, dimola commented on src/main/java/pageObjects/HomePage.java
> +	private WebElement bookCategoryOption;
Correct. It is removed.

2019-02-01 15:07 UTC, dimola commented on configs/Configuration.properties
> +home-page-path=index.php?page=home
Работеше:) Променено е.

2019-02-01 15:09 UTC, dimola commented on src/main/java/dataProviders/ConfigFileReader.java
>  			throw new NotFoundException("Configuration.properties not found at " + propertyFilePath);
Fixed.

2019-02-01 15:10 UTC, dimola commented on src/main/java/dataProviders/ConfigFileReader.java
> +			throw new NotFoundException("implicitlyWait not specified in the Configuration.properties file.");
Fixed.

2019-02-01 15:10 UTC, dimola commented on src/main/java/pageObjects/HomePage.java
> +		if (driver.findElements(By.xpath("//*[@id=\"main-big-col\"]/h3")).size() != 0) {
Fixed.

2019-02-01 15:10 UTC, dimola commented on src/main/java/pageObjects/LoginPage.java
> +	public void isLoginPageOnFocus() {
Fixed.

2019-02-01 15:11 UTC, dimola commented on src/test/java/stepDefinitions/Steps.java
> +		homePage.isHomePageOnFocus();
Fixed

2019-02-01 15:27 UTC, jakimcho approved these changes

2019-02-01 15:27 UTC, merged