Added logout test case
dimola/Ecomm_Testing pull request #7
Opened 2019-02-04 13:18 UTC by olinda88

- Added test case for Logout
- Added LogoutPage.java

2019-02-04 13:52 UTC, jakimcho requested changes

2019-02-04 13:52 UTC, jakimcho commented on src/main/java/pageObjects/HomePage.java
> +	public boolean isLoggedOut() {
@olinda88 Isn't there more understandable way, to check if user is logged out?
I would check in the cucumber THEN step definition if buttons "register" and "login" exist and that button "logout" does not.

2019-02-04 13:52 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +	public void LoggedInUser(String username, String password) {
@olinda88 rename this method to `public void login(String username, String password)`

2019-02-04 13:52 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		Assert.assertTrue(pageObjectManager.getHomePage().isLoggedOut());
@olinda88 Always put sum descriptive message that would support the assert if it fails. This will pay in the future reports

2019-02-04 15:56 UTC, olinda88 commented on src/test/java/stepDefinitions/Steps.java
> +		Assert.assertTrue(pageObjectManager.getHomePage().isLoggedOut());
@jakimcho I forgot to change the following row in the last commit, should I include it and push it again?

Assert.assertTrue("The user is not successfully logged out!", pageObjectManager.getHomePage().isLoggedOut());

2019-02-05 11:25 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/HomePage.java
> +
There is no need for this empty row

2019-02-05 11:26 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/HomePage.java
> +
There is no need for this empty row

2019-02-05 12:04 UTC, merged