Add tc13 and tc16
dimola/Ecomm_Testing pull request #8
Opened 2019-02-04 13:32 UTC by IvayloStoyanov10

- Added TC13  - Leaving the fields empty results in an error message
- Added TC16  - Try to logging 3 times with invalid credentials results in an error message

2019-02-04 14:18 UTC, jakimcho requested changes

2019-02-04 14:18 UTC, jakimcho commented on src/main/java/dataProviders/ConfigFileReader.java
> +
@IvayloStoyanov10 Why did you put new line here?

2019-02-04 14:18 UTC, jakimcho commented on src/main/java/dataProviders/ConfigFileReader.java
> +
@IvayloStoyanov10 Why these new lines?

2019-02-04 14:18 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +	public void enterUsernameAndPassword(String username, String password) {
@IvayloStoyanov10  What is the idea behind this function?

2019-02-04 14:18 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +	public boolean timerIsDisplayed() {
@IvayloStoyanov10 add new line separator between methods.

2019-02-04 14:18 UTC, jakimcho commented on src/main/java/pageObjects/LoginPage.java
> +			}
@IvayloStoyanov10 add new line after loops and conditional block .

2019-02-04 14:18 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +	@Before public void setUp(){
@IvayloStoyanov10 What does this empty method do?

2019-02-04 14:18 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		pageObjectManager.getHomePage().isHomePageOnFocus();
@IvayloStoyanov10  Why did you removed the correct assert an put that instead ?

2019-02-04 14:18 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		pageObjectManager.getLoginPage().enterUsernameAndPassword(username, password);
@IvayloStoyanov10  @olinda88 sync together regarding the `login(username, password)` from login page. Then @IvayloStoyanov10 you can cal three time the `login(username, password)` here to simulate three unsuccessful login attempts. The logic you have implemented in `enterUsernameAndPassword` is awkward and the name of the method does not describe what really happens

2019-02-04 14:18 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		Assert.assertTrue(pageObjectManager.getLoginPage().timerIsDisplayed());
@IvayloStoyanov10 make sure that you use asserts only in the verification steps - > `THEN` keywords

2019-02-04 14:18 UTC, jakimcho commented on src/test/java/stepDefinitions/Steps.java
> +		Assert.assertTrue(pageObjectManager.getLoginPage().timerIsDisplayed());
@IvayloStoyanov10 add a descriptive message when using `assertTrue`. Otherwise it want be really clear in the report what is the problem if assert fails

2019-02-04 14:37 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +		Assert.assertTrue(pageObjectManager.getLoginPage().timerIsDisplayed());
Added messages

2019-02-04 14:37 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +		Assert.assertTrue(pageObjectManager.getLoginPage().timerIsDisplayed());
fixed

2019-02-04 14:38 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +		pageObjectManager.getHomePage().isHomePageOnFocus();
fixed

2019-02-04 14:38 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +	@Before public void setUp(){
fixed: Removed method

2019-02-04 14:44 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/LoginPage.java
> +	public void enterUsernameAndPassword(String username, String password) {
The idea is to leave code outside of the steps.java class. By doing this, I can just call one function in the steps class in order to make the steps more understandable. Also, I believe there is no point in calling 3 functions 3 times each to reach the same goal.

2019-02-04 14:46 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/LoginPage.java
> +			}
fixed

2019-02-04 14:46 UTC, IvayloStoyanov10 commented on src/main/java/pageObjects/LoginPage.java
> +	public boolean timerIsDisplayed() {
fixed

2019-02-04 14:46 UTC, IvayloStoyanov10 commented on src/main/java/dataProviders/ConfigFileReader.java
> +
fixed

2019-02-04 14:46 UTC, IvayloStoyanov10 commented on src/main/java/dataProviders/ConfigFileReader.java
> +
fixed

2019-02-05 11:43 UTC, olinda88 commented on src/test/java/stepDefinitions/Steps.java
> +		pageObjectManager.getLoginPage().login(username, password);
@IvayloStoyanov10 Isn't it better to optimize these 3 lines by using a single method?

2019-02-05 15:21 UTC, IvayloStoyanov10 commented on src/test/java/stepDefinitions/Steps.java
> +		pageObjectManager.getLoginPage().login(username, password);
Not according to Yakim's comments

2019-02-06 07:30 UTC, merged